language: php

sudo: false

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=master WP_MULTISITE=1 PHPLINT=1 PHPUNIT=1
      dist: precise
    - php: 5.6
      env: WP_VERSION=master WP_MULTISITE=1 PHPLINT=1 PHPUNIT=1
      dist: precise
    - php: 5.2.17
      env: WP_VERSION=4.7 WP_MULTISITE=1 PHPLINT=1 PHPUNIT=1
      dist: precise
    - php: 7.0
      env: WP_VERSION=4.7
      dist: trusty
    - php: 7.0
      env: WP_VERSION=4.7
      dist: precise
    - php: 5.6
      env: WP_VERSION=4.7
    - php: 5.6
      env: WP_VERSION=4.6
    - php: 5.6
      env: WP_VERSION=4.5
    - php: 5.6
      env: WP_VERSION=4.5
      dist: precise
    - php: 5.6
      env: WP_VERSION=4.4
    - php: 5.5
      env: WP_VERSION=4.7
    - php: 5.5
      env: WP_VERSION=4.0
    - php: 5.4
      env: WP_VERSION=4.7
    - php: 5.4
      env: WP_VERSION=3.8
    - php: 5.3
      env: WP_VERSION=3.8
      dist: precise

install:
- phpenv local 5.6
- composer selfupdate 1.0.0 --no-interaction
- if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then composer require --dev phpunit/phpunit ^5.7; fi
- composer install --no-interaction
- phpenv local --unset

before_script:
- PLUGIN_SLUG=$(basename $(pwd))
- export WP_DEVELOP_DIR=/tmp/wordpress/
- git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
- cd ..
- cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/formidable"
- cd /tmp/wordpress/
- cp wp-tests-config-sample.php wp-tests-config.php
- sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
- sed -i "s/yourusernamehere/travis/" wp-tests-config.php
- sed -i "s/yourpasswordhere//" wp-tests-config.php
- mysql -e "CREATE DATABASE wordpress_tests;" -uroot
- cd "/tmp/wordpress/src/wp-content/plugins/formidable"
- phpenv rehash

script:
- if [[ "$PHPLINT" == "1" ]]; then find -L .  -path ./vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l; fi
- if [[ "$PHPUNIT" == "1" ]]; then phpunit --group=ajax --exclude-group=pro -c phpunit.xml; fi
- if [[ "$PHPUNIT" == "1" ]]; then phpunit --group=entries --exclude-group=pro -c phpunit.xml; fi
- if [[ "$PHPUNIT" == "1" ]]; then phpunit --group=styles --exclude-group=pro -c phpunit.xml; fi
- if [[ "$PHPUNIT" == "1" ]]; then phpunit --group=emails --exclude-group=pro -c phpunit.xml; fi
- if [[ "$PHPUNIT" == "1" ]]; then phpunit --exclude-group=ajax,pro,entries,styles,emails -c phpunit.xml; fi

notifications:
  email: false
