on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, synchronize ]

name: E2E Test
jobs:
  cypress:
    name: Cypress - Local
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: 'cs2pr'
          coverage: 'none'

      - name: composer install
        run: composer install

      - name: Install node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Set up WP environment
        run: npm run env:start

      - name: Build asset
        run: npm run build

      - name: Test
        run: npm run e2e:run
