on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, synchronize ]

name: E2E Test
jobs:
  cypress:
    runs-on: ubuntu-latest

    name: Cypress
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Composer install
        run: composer install

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Setup PHP
        uses: shivammathur/setup-php@2.30.4
        with:
          php-version: 7.4
          tools: wp-cli

      - name: Install WordPress
        run: |
          wp core install
          wp option update siteurl http://localhost:8889
          wp option update home http://localhost:8889

      - name: Install Plugins
        run: |
          wp plugin uninstall --deactivate --all
          wp plugin install formidable --force

      - name: Set permalinks
        run: |
          wp rewrite structure '/%postname%/' --hard
          wp rewrite flush --hard

      - name: Start PHP web server
        run: sudo php -S localhost:8889 -t /usr/share/nginx/html &

      - name: Build asset
        run: npm run build

      - name: Test
        run: npm run e2e:run
