on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, synchronize ]

name: PHPUnit
jobs:
  build-test:
    if: contains(github.event.pull_request.labels.*.name, 'run tests')
    runs-on: ubuntu-20.04
    env:
      WP_MULTISITE: ${{ matrix.multisite }}
    strategy:
      matrix:
        include:
          # Run tests starting with test_FrmA through test_FrmF
          # Tests are split into 2 groups to run in half the time.
          - php: 7.4
            wordpress: trunk
            multisite: 0
            filter: '/^(test_Frm){1}[A-F]/'
            group: 1
          - php: 8.0
            wordpress: trunk
            multisite: 0
            filter: '/^(test_Frm){1}[A-F]/'
            group: 1
          # Run tests that do not start with test_FrmA through test_FrmF
          # This includes the tests that do not start with test_Frm at all.
          - php: 7.4
            wordpress: trunk
            multisite: 0
            filter: '/^(?!test_Frm[A-F]).*/'
            group: 2
          - php: 8.0
            wordpress: trunk
            multisite: 0
            filter: '/^(?!test_Frm[A-F]).*/'
            group: 2

    name: PHP ${{ matrix.php }} tests in WP ${{ matrix.wordpress }} (${{ matrix.group }}/2)
    steps:
      - uses: actions/checkout@v3.5.0

      # get the PHP version
      - uses: shivammathur/setup-php@2.24.0
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit-polyfills

      - name: Installing WordPress
        run: |
          export WP_DEVELOP_DIR=/tmp/wordpress/
          git clone --depth=1 --branch="${{ matrix.wordpress }}" git://develop.git.wordpress.org/ /tmp/wordpress
          cd ..
          cp -r "${GITHUB_REPOSITORY#*/}" "/tmp/wordpress/src/wp-content/plugins/formidable"
          cd /tmp/wordpress/
          pwd
          cp wp-tests-config-sample.php wp-tests-config.php
          sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
          sed -i "s/yourusernamehere/root/" wp-tests-config.php
          sed -i "s/yourpasswordhere/root/" wp-tests-config.php
      - name: Creating database
        run: |
          sudo /etc/init.d/mysql start
          mysql -u root -proot -e "CREATE DATABASE wordpress_tests;"
      - name: PhpUnit tests
        run: |
          cd "/tmp/wordpress/src/wp-content/plugins/formidable"
          pwd
          phpunit --coverage-clover=coverage.xml --filter '${{ matrix.filter }}'
      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v2
        with:
          files: /tmp/wordpress/src/wp-content/plugins/formidable/coverage.xml
